import type { Metadata } from "next";
import "./ui/globals.css";
import { ThemeProvider } from "@/app/ui/components/theme-provider";
import { Navbar } from "@/app/ui/dashboard/navbar";
import { inter } from "@/app/ui/fonts";
import AppProviders from "@/app/ui/components/appProviders";
import {
  SidebarInset,
  SidebarProvider,
  SidebarTrigger,
} from "@/app/ui/components/sidebar";
import { AppSidebar } from "@/app/ui/dashboard/app-sidebar";
import { auth } from "./api/auth/[...nextauth]/route";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();
  const isSession = session?.user ? true : false;
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${inter.className} antialiased`}>
        <AppProviders>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            {isSession ? (
              <SidebarProvider>
                <AppSidebar />
                <SidebarInset className="max-w-full">
                  <Navbar isSession={isSession} />
                  <main>{children}</main>
                </SidebarInset>
              </SidebarProvider>
            ) : (
              <div className="flex flex-col min-h-screen">
                <Navbar isSession={isSession} />
                <main className="flex-1">{children}</main>
              </div>
            )}
          </ThemeProvider>
        </AppProviders>
      </body>
    </html>
  );
}
