import type { Metadata } from "next";
import "./ui/globals.css";
import { ThemeProvider } from "@/app/ui/components/theme-provider";
import { Navbar } from "@/app/ui/dashboard/navbar";
import { inter } from "@/app/ui/fonts";
import AppProviders from "@/app/ui/components/appProviders";
import { SidebarProvider, SidebarTrigger } from "@/app/ui/components/sidebar";
import { AppSidebar } from "@/app/ui/dashboard/app-sidebar";
import { auth } from "./api/auth/[...nextauth]/route";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();
  const isSession = session?.user ? true : false;
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${inter.className} antialiased overflow-x-hidden`}>
        <AppProviders>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <SidebarProvider>
              <div className="grid grid-cols-[auto_1fr] min-h-screen">
                {isSession ? <AppSidebar /> : ""}
                <div className="flex flex-col flex-1">
                  <Navbar isSession={isSession} />
                  <main className="flex-1 min-w-screen">{children}</main>
                </div>
              </div>
            </SidebarProvider>
          </ThemeProvider>
        </AppProviders>
      </body>
    </html>
  );
}
